apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: component
  lifecycle: experimental
  owner: ${{values.owner | dump}}